auto_port/urls.py
from django.conf.urls import url
from django.contrib import admin
from app01 import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # 项目相关
    url(r'^$', views.index, name='index'),
    url(r'^add_it/$', views.add_it, name='add_it'),
    url(r'^edit_it/(?P<pk>\d+)$', views.edit_it, name='edit_it'),
    url(r'^del_it/(?P<pk>\d+)$', views.del_it, name='del_it'),
    url(r'^upload/(?P<pk>\d+)$', views.upload, name='upload'),


    # 用例相关
    url(r'^case_list/(?P<pk>\d+)$', views.case_list, name='case_list'),
    url(r'^add_case/(?P<pk>\d+)$', views.add_case, name='add_case'),
    url(r'^edit_case/(?P<pk>\d+)/(?P<api_id>\d+)$', views.edit_case, name='edit_case'),
    url(r'^del_case/(?P<pk>\d+)/(?P<api_id>\d+)$', views.del_case, name='del_case'),

    # 执行用例
    url(r'^run_case/(?P<pk>\d+)/(?P<api_id>\d+)$', views.run_case, name='run_case'),
    # 下载用例报告
    url(r'^download_case_report/(?P<pk>\d+)/(?P<api_id>\d+)$', views.download_case_report, name='download_case_report'),

    # 日志相关
    url(r'^logs/list/$', views.logs_list, name='logs_list'),
    url(r'^logs/preview/(?P<logs_id>\d+)$', views.logs_preview, name='logs_preview'),

    # 可视化
    url(r'^echarts_show/$', views.echarts_show, name='echarts_show'),

    # 发邮件
    url(r'^send_email/$', views.send_email, name='send_email'),
]

app01/models.py
from django.db import models


# Create your models here.


class It(models.Model):
    """ 接口项目表 """
    name = models.CharField(verbose_name='项目名称', max_length=32)
    desc = models.TextField(verbose_name='项目描述', max_length=255)
    start_time = models.DateField(verbose_name='项目开始时间')
    end_time = models.DateField(verbose_name='项目结束时间')

    def __str__(self):
        return self.name

    def xxoo(self):
        """覆盖率： 用例通过的数量/总用例数量"""
        if self.api_set.count():
            result = self.api_set.filter(api_pass_status=1).count() / self.api_set.count() * 100
            return "%.2f%%" % result
        return '0'


class Api(models.Model):
    """ 接口用例表 """
    api_sub_it = models.ForeignKey(to='It', verbose_name='所属接口项目')
    api_name = models.CharField(max_length=32, default='', verbose_name='用例名称')
    api_desc = models.TextField(max_length=255, default='', verbose_name='用例描述')
    api_url = models.CharField(max_length=255, default='', verbose_name='请求URL')
    api_method = models.CharField(max_length=32, default='', verbose_name='请求类型')
    api_params = models.CharField(max_length=255, default={}, verbose_name='请求参数')
    api_data = models.CharField(max_length=255, default={}, verbose_name='请求data')
    api_expect = models.CharField(max_length=4196, default={}, verbose_name='预期结果')
    api_report = models.TextField(verbose_name='报告', default='')
    api_run_time = models.DateTimeField(null=True, verbose_name='执行时间')
    api_pass_status_choices = (
        (0, '未通过'),
        (1, '已通过')
    )
    api_pass_status = models.IntegerField(choices=api_pass_status_choices, verbose_name='执行是否通过', default=0)
    api_run_status_choices = (
        (0, '未执行'),
        (1, '已执行'),
    )
    api_run_status = models.IntegerField(choices=api_run_status_choices, verbose_name='是否执行', default=0)

    def __str__(self):
        return self.api_name


class Logs(models.Model):
    """ 用例执行记录
        1. 所属项目
        2. 执行时间
        3. 执行的测试报告
        4. 通过多少，失败多少，共执行了多少用例，通过率是多少
     """
    log_report = models.TextField(verbose_name='报告', default='')
    log_sub_it = models.ForeignKey(to='It', verbose_name='所属接口项目')
    log_run_time = models.DateTimeField(null=True, verbose_name='log日志产生时间', auto_now_add=True)
    log_pass_count = models.IntegerField(verbose_name='通过数量')
    log_failed_count = models.IntegerField(verbose_name='失败数量')
    log_errors_count = models.IntegerField(verbose_name='报错数量')
    log_run_count = models.IntegerField(verbose_name='执行用例总数')

    def pass_rate(self):
        """  通过率 """
        if self.log_run_count:
            result = self.log_pass_count / self.log_run_count * 100
            if result:
                return "%.f%%" % (result)
            else:
                return 0
        else:
            return 0

    class Meta:
        ordering = ['-log_run_time']

templates/add_It.html
{% extends 'layout.html' %}

{% block content-head %}
    <h5>添加项目</h5>
{% endblock %}


{% block content-body %}
    <form method="post" novalidate>
        {% csrf_token %}
        {% for foo in form %}
            <div class="form-group">
                <div>
                    <label for="{{ foo.id_for_label }}">{{ foo.label }}</label>
                    {{ foo }}
                </div>
                <span style="color: red;">{{ foo.errors.0 }}</span>
            </div>

        {% endfor %}

        <button type="submit" class="btn btn-success">提交</button>
    </form>

{% endblock %}

templates/case_list.html
{% extends 'layout.html' %}
{% load static %}

{% block nav %}
    <ol class="breadcrumb float-sm-right">
        <li class="breadcrumb-item"><a href="{% url 'index' %}">首页</a></li>
        <li class="breadcrumb-item"><a href="{% url 'case_list' it_obj.pk %}">{{ it_obj.name }}</a></li>
        <li class="breadcrumb-item active">用例列表</li>
    </ol>
{% endblock %}




{% block content %}
    <div class="card card-primary">
        <div class="card-header">
            <a href="{% url 'add_case' it_obj.id %}">添加用例</a>
        </div>
    </div>

    <table class="table table-striped table-hover table-bordered">
        <thead>
        <tr>
            <th>选择</th>
            <th>序号</th>
            <th>名称</th>
            <th>描述</th>
            <th>请求url</th>
            <th>请求类型</th>
            <th>请求参数</th>
            <th>请求data</th>
            <th>预期值</th>
            <th>用例报告</th>
            <th>通过状态</th>
            <th>是否执行</th>
            <td>操作</td>
        </tr>
        </thead>

        <tbody>
        {% for api in api_list %}
            <tr>
                <td>
                    <input type="checkbox" value="{{ api.pk }}" name="checkbox_list">
                </td>
                <td>{{ forloop.counter }}</td>
                <td>{{ api.api_name }}</td>
                <td title="{{ api.api_desc }}">{{ api.api_desc | truncatechars:10 }}</td>
                <td title="{{ api.api_url }}">{{ api.api_url | truncatechars:10 }}</td>
                <td>{{ api.api_method }}</td>
                <td>{{ api.api_params }}</td>
                <td>{{ api.api_data }}</td>
                <td>{{ api.api_expect }}</td>
                {% if api.api_report %}
                    <td><a href="{% url 'download_case_report' it_obj.id api.id %}">下载</a></td>
                {% else %}
                    <td>无</td>
                {% endif %}

                <td>{{ api.get_api_pass_status_display }}</td>
                <td>{{ api.get_api_run_status_display }}</td>
                <td>
                    <a type="button" class="btn btn-primary btn-xs"
                       href="{% url 'edit_case' it_obj.id api.id %}">
                        <i class="fa fa-edit" aria-hidden="true"></i>编辑
                    </a>

                    <a type="button" class="btn btn-danger btn-xs"
                       href="{% url 'del_case' it_obj.id api.id %}">
                        <i class="fa fa-trash" aria-hidden="true"></i>删除
                    </a>

                    <a type="button" class="btn btn-info btn-xs"
                       href="{% url 'run_case' it_obj.id api.id %}">
                        <i class="fa fa-book" aria-hidden="true"></i>执行
                    </a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <div>
        <input type="button" value="批量执行" class="btn btn-success" id="mulExecute">
    </div>

{% endblock %}

{% block js %}
{#    <script src="https://cdn.bootcdn.net/ajax/libs/sweetalert/2.1.2/sweetalert.min.js"></script>#}
    <script src="{% static 'sweetalert.js' %}"></script>
    <script>
    $('#mulExecute').click(function () {
        var api_id_list = new Array();

        $.each($('input[name="checkbox_list"]:checked'), function (index, item) {
            // console.log(index, item) // 1 <input type=​"checkbox" value=​"5" name=​"checkbox_list">​
            api_id_list.push($(item).val())
        });

        // console.log(api_id_list)   // (2) ['4', '5']
        if(api_id_list.length == 0){
            swal({
                'title': '你至少得勾选一个用例吧，铁汁！',
                'text': '我说的',
                'icon': 'http://127.0.0.1:8000/static/AdminLTE-master/dist/img/user2-160x160.jpg'
            })
        }else {
            // 发送ajax请求到后端
            $.ajax({
                'url': '{% url "run_case" it_obj.id 0 %}',
                'type': 'POST',
                'data': {'api_id_list': JSON.stringify(api_id_list)},   // 序列化：数组->字符串
                success: function (res) {
                    window.location = res['path']
                }
            })
        }


    })
    </script>
{% endblock %}

templates/change_It.html
{% extends 'layout.html' %}

{% block nav %}
    <ol class="breadcrumb float-sm-right">
        <li class="breadcrumb-item"><a href="{% url 'index' %}">首页</a></li>
        {% if flag %}
            <li class="breadcrumb-item active">编辑项目</li>

        {% else %}
            <li class="breadcrumb-item active">添加项目</li>

        {% endif %}
    </ol>
{% endblock %}


{% block content %}
    <form method="post" novalidate>
        {% csrf_token %}
        {% for foo in form %}
            <div class="form-group">
                <div>
                    <label for="{{ foo.id_for_label }}">{{ foo.label }}</label>
                    {{ foo }}
                </div>
                <span style="color: red;">{{ foo.errors.0 }}</span>
            </div>

        {% endfor %}

        <button type="submit" class="btn btn-success">提交</button>
    </form>

{% endblock %}

templates/change_case.html
{% extends 'layout.html' %}

{% block nav %}
    <ol class="breadcrumb float-sm-right">
        <li class="breadcrumb-item"><a href="{% url 'index' %}">首页</a></li>
        <li class="breadcrumb-item"><a href="{% url 'case_list' it_obj.pk %}">{{ it_obj.name }}</a></li>
        {% if flag %}
            <li class="breadcrumb-item active">编辑用例</li>

        {% else %}
            <li class="breadcrumb-item active">添加用例</li>

        {% endif %}
    </ol>
{% endblock %}


{% block content %}
    <form method="post" novalidate>
        {% csrf_token %}
        {% for foo in form %}
            <div class="form-group">
                <div>
                    <label for="{{ foo.id_for_label }}">{{ foo.label }}</label>
                    {{ foo }}
                </div>
                <span style="color: red;">{{ foo.errors.0 }}</span>
            </div>

        {% endfor %}

        <button type="submit" class="btn btn-success">提交</button>
    </form>

{% endblock %}

templates/echarts_show.html
{% extends 'layout.html' %}
{% load static %}

{% block nav %}
    <ol class="breadcrumb float-sm-right">
        <li class="breadcrumb-item"><a href="{% url 'index' %}">首页</a></li>
        <li class="breadcrumb-item active">数据可视化</li>
    </ol>
{% endblock %}

{% block content %}
    <div class="card card-info">
        <div class="card-header">
            <h3 class="card-title">数据用例近一年总用例数走势图</h3>

            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse"><i
                        class="fas fa-minus"></i>
                </button>
                <button type="button" class="btn btn-tool" data-card-widget="remove"><i
                        class="fas fa-times"></i>
                </button>
            </div>
        </div>
        <div class="card-body">
            <div class="chart">
                <div id="LineRace"
                     style="min-height: 250px; height: 400px; max-height: 450px; max-width: 100%; "></div>
            </div>
        </div>
        <!-- /.card-body -->
    </div>

    <div class="row">
        <!-- 数据用例通过情况 -->
        <div class="col-md-6">
            <div class="card card-info">
                <div class="card-header">
                    <h3 class="card-title">数据用例通过情况</h3>

                    <div class="card-tools">
                        <button type="button" class="btn btn-tool" data-card-widget="collapse"><i
                                class="fas fa-minus"></i>
                        </button>
                        <button type="button" class="btn btn-tool" data-card-widget="remove"><i
                                class="fas fa-times"></i>
                        </button>
                    </div>
                </div>
                <div class="card-body">
                    <div class="chart">
                        <div id="PassPie"
                             style="min-height: 250px; height: 400px; max-height: 450px; max-width: 100%; "></div>
                    </div>
                </div>
                <!-- /.card-body -->
            </div>

        </div>

        <!-- 数据用例执行情况 -->
        <div class="col-md-6">
            <div class="card card-info">
                <div class="card-header">
                    <h3 class="card-title">数据用例执行情况</h3>

                    <div class="card-tools">
                        <button type="button" class="btn btn-tool" data-card-widget="collapse"><i
                                class="fas fa-minus"></i>
                        </button>
                        <button type="button" class="btn btn-tool" data-card-widget="remove"><i
                                class="fas fa-times"></i>
                        </button>
                    </div>
                </div>
                <div class="card-body">
                    <div class="chart">
                        <div id="ExecutePie"
                             style="min-height: 250px; height: 400px; max-height: 450px; max-width: 100%; "></div>
                    </div>
                </div>
                <!-- /.card-body -->
            </div>

        </div>
    </div>
{% endblock %}


{% block js %}
    <script src="{% static 'echarts.min.js' %}"></script>
    <script>

        // var ROOT_PATH = 'https://127.0.0.1/examples';
        var ROOT_PATH = 'https://echarts.apache.org/examples';

        // 用例通过/未通过情况   饼图
        function PassPie(title, data) {
            // 1. 实例化 echarts 对象
            var chartDom = document.getElementById('PassPie');
            var myChart = echarts.init(chartDom);
            var option;

            // 2， 配置参数
            option = {
                title: {
                    text: '用例执行通过情况',
                    subtext: 'Fake Data',
                    left: 'center'
                },
                tooltip: {
                    trigger: 'item',
                    formatter: '{a} <br/>{b} : {c} ({d}%)'
                },
                legend: {
                    bottom: 10,
                    left: 'center',
                    data: title
                },
                series: [
                    {
                        type: 'pie',
                        radius: '65%',
                        center: ['50%', '50%'],
                        selectedMode: 'single',
                        data: data,
                        emphasis: {
                            itemStyle: {
                                shadowBlur: 10,
                                shadowOffsetX: 0,
                                shadowColor: 'rgba(0, 0, 0, 0.5)'
                            }
                        }
                    }
                ]
            };

            // 3. setoption
            option && myChart.setOption(option);
        }

        // 用例执行/未执行情况   饼图
        function ExecutePie(title, data) {
            // 1. 实例化 echarts 对象
            var chartDom = document.getElementById('ExecutePie');
            var myChart = echarts.init(chartDom);
            var option;

            // 2， 配置参数
            option = {
                title: {
                    text: '用例执行情况',
                    subtext: 'Fake Data',
                    left: 'center'
                },
                tooltip: {
                    trigger: 'item',
                    formatter: '{a} <br/>{b} : {c} ({d}%)'
                },
                legend: {
                    bottom: 10,
                    left: 'center',
                    data: title
                },
                series: [
                    {
                        type: 'pie',
                        radius: '65%',
                        center: ['50%', '50%'],
                        selectedMode: 'single',
                        data: data,
                        emphasis: {
                            itemStyle: {
                                shadowBlur: 10,
                                shadowOffsetX: 0,
                                shadowColor: 'rgba(0, 0, 0, 0.5)'
                            }
                        }
                    }
                ]
            };

            // 3. setoption
            option && myChart.setOption(option);
        }

        // 用例近一年数据情况   折线图
        function LineRace(title, data) {
            var chartDom = document.getElementById('LineRace');
            var myChart = echarts.init(chartDom);
            var option;

            option = {
                xAxis: {
                    type: 'category',
                    boundaryGap: false,
                    data: title
                },
                yAxis: {
                    type: 'value'
                },
                series: [
                    {
                        data: data,
                        type: 'line',
                        areaStyle: {}
                    }
                ]
            };

            option && myChart.setOption(option);

        }


        function init() {
            $.ajax({
                'url': '{% url "echarts_show" %}',
                'type': 'POST',
                'data': '',
                success: function (res) {
                    // console.log(res);
                    // 用例通过/未通过情况   饼图
                    PassPie(res['data_dict']['pass_pie']['title'], res['data_dict']['pass_pie']['data']);
                    // 用例执行/未执行情况   饼图
                    ExecutePie(res['data_dict']['execute_pie']['title'], res['data_dict']['execute_pie']['data']);
                    // 用例近一年数据情况   折线图
                    LineRace(res['data_dict']['line_race']['title'], res['data_dict']['line_race']['data']);

                }
            })
        }

        init();
    </script>
{% endblock %}

templates/index.html
{% extends 'layout.html' %}

{% block nav %}
    <ol class="breadcrumb float-sm-right">
        <li class="breadcrumb-item"><a href="{% url 'index' %}">首页</a></li>
        <li class="breadcrumb-item active">项目列表</li>
    </ol>
{% endblock %}




{% block content %}
    {% if it_obj_list %}
        <div class="card card-primary">
            <div class="card-header">
            <a href="{% url 'add_it' %}">添加项目</a>
        </div>
        <table class="table table-striped table-hover table-bordered">
            <thead>
            <tr>
                <th>序号</th>
                <th>名称</th>
                <th>描述</th>
                <th>开始时间</th>
                <th>结束时间</th>
                <th>用例数据</th>
                <th>覆盖率</th>
                <th>操作</th>
            </tr>
            </thead>

            <tbody>
            {% for foo in it_obj_list %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ foo.name }}</td>
                    <td>{{ foo.desc }}</td>
                    <td>{{ foo.start_time }}</td>
                    <td>{{ foo.end_time }}</td>
                    <td>{{ foo.api_set.count }}</td>
                    <td>{{ foo.xxoo }}</td>  <!--用例通过的数量 除以 总用例数量-->
                    <td>
                        <a type="button" class="btn btn-primary btn-xs"
                           href="{% url 'edit_it' foo.id %}">
                            <i class="fa fa-edit" aria-hidden="true"></i>编辑
                        </a>

                        <a type="button" class="btn btn-danger btn-xs"
                           href="{% url 'del_it' foo.id %}">
                            <i class="fa fa-trash" aria-hidden="true"></i>删除
                        </a>

                        <a type="button" class="btn btn-info btn-xs"
                           href="{% url 'add_case' foo.id %}">
                            <i class="fa fa-address-book" aria-hidden="true"></i>添加用例
                        </a>

                        <a type="button" class="btn btn-default btn-xs"
                           href="{% url 'upload' foo.id %}">
                            <i class="fa fa-mug-hot" aria-hidden="true"></i>批量导入用例
                        </a>

                        <a type="button" class="btn btn-success btn-xs"
                           href="{% url 'case_list' foo.id %}">
                            <i class="fa fa-sad-cry" aria-hidden="true"></i>查看用例
                        </a>
                    </td>
                </tr>
            {% endfor %}

            </tbody>
        </table>
    {% else %}
        <div>此处还没有项目，去 <a href="{% url 'add_it' %}">创建</a></div>
    {% endif %}
{% endblock %}

templates/logs_list.html
{% extends 'layout.html' %}
{% load static %}

{% block nav %}
    <ol class="breadcrumb float-sm-right">
        <li class="breadcrumb-item"><a href="{% url 'index' %}">首页</a></li>
        <li class="breadcrumb-item active">日志列表</li>
    </ol>
{% endblock %}




{% block content %}
    <div class="card card-primary">
        <div class="card-header">

        </div>
    </div>

    <table class="table table-striped table-hover table-bordered">
        <thead>
        <tr>
            <th>序号</th>
            <th>所属项目</th>
            <th>创建时间</th>
            <th>执行用例总数</th>
            <th>用例失败数</th>
            <th>用例报错数</th>
            <th>用例通过数</th>
            <th>通过率</th>
            <th>用例报告</th>
        </tr>
        </thead>

        <tbody>
        {% for logs_obj in logs_obj_list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ logs_obj.log_sub_it.name }}</td>
                <td>{{ logs_obj.log_run_time }}</td>
                <td>{{ logs_obj.log_run_count }}</td>
                <td>{{ logs_obj.log_failed_count }}</td>
                <td>{{ logs_obj.log_errors_count }}</td>
                <td>{{ logs_obj.log_pass_count }}</td>
                <td>{{ logs_obj.pass_rate }}</td>
                <td><a href="{% url 'logs_preview' logs_obj.id %}">预览</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>


{% endblock %}

templates/logs_preview.html
{% extends 'layout.html' %}



{% block content %}
    <div class="card card-info">
        <div class="card-header">
            <h3 class="card-title">【{{ log_obj.log_sub_it.name }}】 的日志预览 </h3>

            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse"><i
                        class="fas fa-minus"></i>
                </button>
                <button type="button" class="btn btn-tool" data-card-widget="remove"><i
                        class="fas fa-times"></i>
                </button>
            </div>
        </div>
        <div class="card-body">
            <div class="chart">
                <div id="logs"
                         style="min-height: 250px; height: 100%; max-width: 100%; ">

                        {{ log_obj.log_report| safe }}
                    </div>


                <form action="" method="post">
                    <div style="float: right">
                        <a href="{% url 'logs_list' %}"><input type="button" value="返回" class="btn btn-info"></a>
                       <input type="submit" value="下载" class="btn btn-success">
                    </div>
                </form>
            </div>
        </div>
        <!-- /.card-body -->
    </div>
{% endblock %}

templates/upload.html
{% extends 'layout.html' %}


{% block nav %}
    <ol class="breadcrumb float-sm-right">
        <li class="breadcrumb-item"><a href="{% url 'index' %}">首页</a></li>
        <li class="breadcrumb-item active">批量导入用例</li>
    </ol>
{% endblock %}

{% block content %}
    <div class="card-body">
        <div class="alert alert-warning alert-dismissible" id="p1">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h5><i class="icon fas fa-ban"></i> 重要提示!</h5>
            <span id="error">
            这里只能上传Excel文件,
        Excel表格设计字段的时候，参考数据的字段设计，方便上传文件。
        </span>
        </div>


        <div class="form-group">
            <label for="exampleInputFile">文件上传</label>
            <div class="input-group">
                <div class="custom-file">
                    <input type="file" class="custom-file-input" id="ajaxFile">
                    <label class="custom-file-label" for="">请选择文件</label>
                </div>
                <div class="input-group-append">
                    <span class="input-group-text" id="ajaxBtn">Upload</span>
                </div>
            </div>
        </div>
        <span>{{ errors }}</span>
    </div>
{% endblock %}


{% block js %}

    <script>
        $("#ajaxBtn").click(function () {
            // 首先，实例化一个formdata对象
            var formData = new FormData();
            // 然后使用formdata的append来添加数据，即获取文件对象
            // var file_obj = $("#ajaxFile")[0].files[0];    // 使用jQuery获取文件对象
            var file_obj = document.getElementById('ajaxFile').files[0];   // 使用dom也行
            formData.append('f1', file_obj);

            $.ajax({
                url: "{% url 'upload' it_obj_pk%}",
                type: "POST",
                data: formData,
                processData: false,
                contentType: false,   // 避免 JQuery 对请求头content_type进行操作
                success: function (res) {
                    console.log(res);
                    if (res['status'] == 500) {
                        $("#p1").attr("class", 'alert alert-danger alert-dismissible');
                        $("#error").text(res['errors'])
                    } else {
                        window.location.href = res['path']
                    }
                }
            })
        })
    </script>
{% endblock %}